-- migrations/0003_rs_verify.sql
-- RS parlay account verification via edgebot DM flow.
-- Apply with: npx wrangler d1 execute edge-db --remote --file=migrations/0003_rs_verify.sql

-- Pending verification codes (generated by edgebot DM reply, consumed on verify)
CREATE TABLE IF NOT EXISTS rs_verify_codes (
  code        TEXT    PRIMARY KEY,
  rs_user_id  TEXT    NOT NULL,
  rs_username TEXT,
  channel_id  TEXT    NOT NULL,
  created_at  INTEGER NOT NULL,
  expires_at  INTEGER NOT NULL
);

-- Track which channels edgebot has already processed (avoid double-replying)
-- Key: edgebot_dm_seen_{channelId} → stored in odds_cache (no new table needed)

-- Add parlay verification columns to real_auth
ALTER TABLE real_auth ADD COLUMN parlay_verified    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE real_auth ADD COLUMN parlay_verified_at INTEGER;
